splitio/split-synchronizer

conf/sections.go
entrypoint.sh
splitio/commitversion.go
splitio/storage/redis/client.go
splitio/storage/redis/client_test.go
splitio/version.go

* [SDKS-269]: Redis Cluster Support
* Added `keyHashTags` for redis Cluster
* N/A
* New version to release: `1.8.0-rc4`

[SDKS-269]: Redis Cluster Sync

---

main.go
splitio/storage/interfaces.go
splitio/storage/redis/events_test.go
splitio/storage/redis/impression.go
splitio/storage/redis/impression_test.go
splitio/task/postimpressions_test.go
splitio/version.go
splitio/web/admin/controllers/controllers.go
splitio/web/admin/router.go

* 
* Bullet 1
* Bullet 2
* Bullet 1
* Bullet 2
* Version

[SDKs-236]: Queue Size Endpoints

---

.travis.yml
docker_push
release/versions.pos.html
release/versions.pre.html
release/versions.tpl.html

INFRA-1014
* Use TravisCI for testing, building and deploying.
* Check Travis CI output.

Travis CI build and Deploy

---

CHANGES.txt
splitio/storage/redis/split.go
splitio/storage/redis/traffics.go
splitio/task/fetchsplits.go
splitio/version.go

* [NO TICKET]
* Updated the logic of updating traffic type storage.

[NO-TICKET]: Fixed updateSplits

---

CHANGES.txt
splitio/commitversion.go
splitio/producer/initialization.go
splitio/proxy/initialization.go
splitio/task/healtcheck.go
splitio/task/healthcheck_test.go
splitio/version.go
splitio/web/admin/controllers/controllers.go
splitio/web/admin/controllers/controllers_test.go

* [SDKS-795: Add healthy since info](https://splitio.atlassian.net/browse/SDKS-795)
* Added healtheck task to check environment status.
* Added an inmemory record on when was the last time that everything worked.
* `2.3.1`

[SDKS-795]: Add healthy since info

---

splitio/task/healtcheck.go
splitio/web/dashboard/HTMLtemplates/layout.tpl.go
splitio/web/dashboard/dashboard.go

* [SDKS-764: Add healthcheck into Dashboard](https://splitio.atlassian.net/browse/SDKS-764)
* Add new cards stats for healthcheck in Dashboard.
* Added new method in healthcheck that returns the timestamp in seconds when the Sync was ok.
*`2.3.1`

[SDKS-764]: Add healthcheck into Dashboard

---

splitio/commitversion.go
splitio/storage/redis/split.go
splitio/version.go

* Added check if split exist before decrementing tt
* Version

[INTERNAL]: TT Fix

---

CHANGES.txt
log/helper.go
splitio/commitversion.go
splitio/version.go

* [NO TICKET]
* Removed @here in slack messages
*`2.4.1`

[NO-TICKET]: Remove @here in slack messages

---

CHANGES.txt
splitio/commitversion.go
splitio/producer/initialization.go
splitio/storage/interfaces.go
splitio/task/evictioncalculator.go
splitio/task/evictioncalculator_test.go
splitio/task/postevents.go
splitio/task/postimpressions.go
splitio/version.go
splitio/web/dashboard/HTMLtemplates/layout.tpl.go

* [SDKS-796: Add formula to go sync dashboard](https://splitio.atlassian.net/browse/SDKS-796)
* Added eviction calculator task for Events and Impressions when is running in producer mode.
* Added eviction metrics in Dashboard.
* Moved sync version to the top of the dashboard.
* Version

[SDKS-796]: Add formula to go sync dashboard

---

.github/pull_request_template.md
CHANGES.txt
CONTRIBUTORS-GUIDE.md
README.md

* Updated `CHANGES.txt`
* Updated `README.md`
* Added `CONTRIBUTORS-GUIDE.md`

updated documentation

---

main.go

fixed issue when test run in go 13

---

entrypoint.sh
splitio/api/post.go
splitio/commitversion.go
splitio/nethelper/netip.go
splitio/task/postimpressions_test.go

replaced to NA

---

CHANGES.txt
splitio/proxy/controllers.go
splitio/proxy/controllers_test.go
splitio/proxy/router.go
splitio/version.go

- Added auth endpoint to support push.
- Execute `go test ./...`
- Perform an authentication with a SDK that supports push and check the response.
- This is a placeholder logic until we release push.

Added auth for proxy

---

Dockerfile

Create a group and user called split-synchronizer and use it ro run the software.
Docker build and run it.

Add another user

---

.travis.yml

**Every branch:**
Test and Docker push (unstable).
**Pull request or master:**
Test and build binaries.
**Master:**
Test, build and deploy to S3.
**Cron (daily):**
Docker push (stable). 
**How it looks in Artifactory:**

Docker push (unstable) containers on every branch

---

conf/sections.go
conf/util.go
entrypoint.sh

added config

---

CHANGES.txt

updated changelog

---

splitio/common/dtos.go
splitio/producer/worker/impression.go
splitio/producer/worker/util.go
splitio/proxy/controllers.go
splitio/version.go

added deserialization for proxy to work with listener

---

CHANGES.txt

more specigic in changelog

---

CONTRIBUTORS-GUIDE.md

Updated contributors guide title

---

CHANGES.txt
Dockerfile
splitio/proxy/controllers.go
splitio/proxy/router.go
splitio/proxy/router_test.go
splitio/version.go

added v2/auth for proxy

---

splitio/producer/conf/sections.go
splitio/proxy/conf/sections.go

- Proxy and Producer healthcheck configs

Proxy and Producer healthcheck configs

---

CHANGES.txt
splitio/admin/controllers/observability.go
splitio/commitversion.go
splitio/provisional/healthcheck/application/counter/threshold.go
splitio/proxy/storage/telemetryts.go
splitio/proxy/storage/telemetryts_test.go
splitio/version.go

- Added missing mysegments entry in timesliced telemetry
- Added cumulative telemetry to the observability payload

some observability fixes and additions

---

.github/workflows/update-license-year.yml
CHANGES.txt
LICENSE
splitio/commitversion.go
splitio/producer/util.go
splitio/version.go

support tls for redis connections in cluster/sentinel modes

---

.github/workflows/cd.yml

Use IAM Role instead of keys
Merge it.

Use IAM Role instead of keys

---

CHANGES.txt
go.mod
go.sum
splitio/version.go

bumping split commons for starting cn from -1

---

.github/workflows/ci.yml

added scan task

---

CHANGES.txt
go.mod
go.sum
splitio/commitversion.go
splitio/version.go

fixed auth healtcheck

---

go.mod
go.sum
splitio/producer/conf/sections.go
splitio/producer/initialization.go
splitio/producer/task/impcounts.go
splitio/producer/task/uniquekeys.go
splitio/producer/util.go
splitio/producer/worker/impcounts.go

- Add gorutine to read and send Impression Counts

Add gorutine to read and send Impression Counts

---

CHANGES.txt
docker/Dockerfile.proxy
docker/Dockerfile.synchronizer
splitio/commitversion.go
splitio/version.go

updated alpine version in dockerfiles

---

CHANGES.txt
go.mod
go.sum
splitio/commitversion.go
splitio/producer/conf/sections.go
splitio/producer/util.go
splitio/version.go

added user for redis cfg

---

.github/workflows/cd.yml
.github/workflows/ci.yml

use awk to pare version independently of the line

parse version by regex, not line count

---

cmd/synchronizer/flag_set_validation_error_test.go
cmd/synchronizer/main.go
splitio/producer/initialization_test.go
splitio/producer/util.go

Adding flagsets on hash

---

go.mod
go.sum
splitio/proxy/initialization.go

Adding telemetry init

---

CHANGES.txt
docker/Dockerfile.proxy
docker/Dockerfile.synchronizer
go.mod
go.sum
splitio/commitversion.go
splitio/producer/initialization.go
splitio/version.go

Updating docker image vulnerabilities and split-commons version

---

splitio/admin/admin.go
splitio/admin/controllers/dashboard.go
splitio/admin/views/dashboard/main.go
splitio/commitversion.go
splitio/producer/conf/sections.go
splitio/producer/initialization.go
splitio/producer/initialization_test.go
splitio/producer/util.go
splitio/proxy/conf/sections.go
splitio/proxy/initialization.go

Adding spec version to dashboard.

---

splitio/proxy/caching/caching.go
splitio/proxy/caching/workers.go
splitio/proxy/caching/workers_test.go
splitio/proxy/controllers/sdk.go

Update Mem surrogate key

---

.github/workflows/docker.yml
.github/workflows/s3.yml
.github/workflows/test.yml
.github/workflows/unstable.yml
splitio/version.go

- Change base branch to `main`
- Push to ECR
- remove Lacework

Add ECR docker registry
